### ISSUE TITLE
Chrono::Iterator occur Infinite loop when invalid date given

### ISSUE THREAD

**Issue by wakaba260** [r7kamura/chrono#2]
example:

```
Chrono::Iterator.new("* * 31 11 *").next #=> infinite loop
```

bug spot:
https://github.com/r7kamura/chrono/blob/master/lib/chrono/next_time.rb#L24

How you do try validate of datetime check?

**Comment by r7kamura** [comment]
@wakaba260 Thanks for reporting, but hmm... I have no idea for now...

**Comment by wakaba260** [comment]
I have no idea too...
It might want to change implement, because Iterator#next be long period of execution time when long futures given.

**Comment by r7kamura** [comment]
More strict validation on `Chrono::Iterator.new` may be able to resolve this issue (just idea).

**Comment by r7kamura** [comment]
This problem is not solved but I still have no idea yet too 😩
